import { Before, After, BeforeAll, AfterAll, Status } from '@cucumber/cucumber';
import { chromium } from '@playwright/test';
import { PlaywrightWorld } from './world';
import { config } from '../utils/config';

/**
 * TEMPLATE / EXAMPLE — NOT A DROP-IN PRODUCTION IMPLEMENTATION
 *
 * Purpose: provide the lifecycle structure for Playwright + Cucumber E2E tests.
 * Copy this file into the target project and adapt it after reviewing the
 * project's browser, authentication, test-account, and cleanup requirements.
 *
 * Rules for maintainers and automation agents:
 * - Never hard-code credentials, tokens, real URLs, or default test accounts.
 * - Use CI-managed secrets or project-owned environment configuration only.
 * - Do not run destructive or authenticated scenarios against production
 *   without explicit user authorization and a reviewed test account.
 * - Treat storage-state files as sensitive: generate them through a reviewed
 *   setup flow and keep them out of version control.
 * - If a required project-specific setup is missing, fail clearly instead of
 *   inventing authentication, storage, or cleanup behavior.
 */

// ── Global setup (runs once before ALL scenarios) ──────────────────────────
BeforeAll(async function () {
  // Use for: starting a test server, seeding a DB, pre-generating shared tokens
  // WARNING: `this` is NOT a World instance here — no page/browser/context access
});

// ── Per-scenario setup (runs before EACH scenario) ─────────────────────────
Before(async function (this: PlaywrightWorld) {
  this.browser = await chromium.launch({ headless: config.headless, slowMo: config.slowMo });
  this.context = await this.browser.newContext({
    baseURL: config.baseUrl,
    viewport: { width: 1280, height: 720 },
  });
  this.page = await this.context.newPage();
  this.page.setDefaultTimeout(config.timeout);
});

// ── Tagged hook — only runs before @authenticated scenarios ────────────────
/**
 * Authentication is intentionally a project-owned adaptation point.
 *
 * Do not assume a login endpoint, cookie name, token shape, or storage-state
 * path in a reusable template. Authentication state files can contain cookies
 * and browser storage that impersonate a test account, so they must be generated by a
 * reviewed setup flow and excluded from version control.
 */
function authenticationSetupRequired(): never {
  throw new Error(
    '[hooks.ts] @authenticated is intentionally unconfigured. ' +
      'Create a project-owned authentication setup before using this tag. ' +
      'If the project reuses Playwright storage state, pass a verified and gitignored ' +
      'state file to browser.newContext({ storageState: authFile }) when creating the context. ' +
      'Do not call context.storageState({ path }) to load state: that method writes the current state.',
  );
}

// Tagged hook: target projects must replace this fail-closed adaptation point
// with their own reviewed authentication setup.
Before({ tags: '@authenticated' }, async function () {
  authenticationSetupRequired();
});

// ── Per-scenario teardown (runs after EACH scenario) ───────────────────────
After(async function (this: PlaywrightWorld, scenario) {
  try {
    if (scenario.result?.status === Status.FAILED) {
      // Embed screenshot in HTML report
      const screenshot = await this.page.screenshot({ fullPage: true });
      this.attach(screenshot, 'image/png');
    }
  } finally {
    // Always close — even if screenshot capture fails
    await this.page?.close();
    await this.context?.close();
    await this.browser?.close();
  }
});

// ── Global teardown (runs once after ALL scenarios) ────────────────────────
AfterAll(async function () {
  // Use for: stopping a test server, removing test DB records, revoking shared auth
  // WARNING: `this` is NOT a World instance here
});
